export enum EventIdentifiers {
    REQUESTED_CREATE_PAYMENT = 'requested_create_payment',
    REQUESTED_CREATE_PRODUCT = 'requested_create_product',
    REQUESTED_MODIFY_PRODUCT = 'requested_modify_product',
    REQUESTED_GET_API_STATE = 'requested_get_api_state',
    REQUESTED_CREATE_SHOP = 'requested_create_shop',
    REQUESTED_MODIFY_SHOP = 'requested_modify_shop',
    REQUESTED_DELETE_SHOP = 'requested_delete_shop',
    REQUESTED_GET_USER_PUBLIC_PROFILE = 'requested_get_user_public_profile',
    REQUESTED_GET_USER_PRIVATE_SETTINGS = 'requested_get_user_private_settings',
    REQUESTED_GET_SHOP = 'requested_get_shop',
    REQUESTED_GET_PRODUCT = 'requested_get_product',
    REQUESTED_LOG_IN = 'requested_log_in',
    REQUESTED_LOG_OUT = 'requested_log_out',
    REQUESTED_REGISTER_BY_MAIL = 'requested_register_by_mail',
    START = 'start',
    STOP = 'stop',
}
