BASEDIR=$(dirname "$0")

DATABASE_HOST="open-mt-database"
DATABASE_PORT="5432"
DATABASE_NAME="open_mt"
DATABASE_USER="postgres"
DATABASE_PASSWORD="postgres"
DATABASE_URL="postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?pool_timeout=120&connect_timeout=120"

export BASEDIR
export DATABASE_URL